import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/operations-ui";
import { Link } from "@tanstack/react-router";
import { ArrowRight, ClipboardCheck, Headphones, PackageCheck, RadioTower, Wrench } from "lucide-react";

export const Route = createFileRoute("/dashboards")({ head: () => ({ meta: [{ title: "Role Dashboards · Vortex Visual" }, { name: "description", content: "Role-specific operational workspaces for Vortex Visual teams." }] }), component: DashboardsPage });
const roles = [{ name: "CCR", icon: Headphones, kpi: "11 client follow-ups", detail: "Booking intake, confirmations, and payment reminders." }, { name: "Chief Technician", icon: Wrench, kpi: "4 technical approvals", detail: "Review screen specs, BOM, and field readiness." }, { name: "Operation Officer", icon: RadioTower, kpi: "6 active dispatches", detail: "Coordinate assembly schedules and team movement." }, { name: "Technician", icon: ClipboardCheck, kpi: "3 assigned jobs", detail: "Accept assignments, prepare equipment, and close work." }, { name: "Storekeeper", icon: PackageCheck, kpi: "9 checkouts today", detail: "Issue, receive, inspect, and reconcile inventory." }];
function DashboardsPage() { return <AppShell><PageHeader eyebrow="Role Workspaces" title="Operational Dashboards" description="Focused queues and controls for every team in the booking lifecycle." />
  <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{roles.map(({ name, icon: Icon, kpi, detail }) => <article key={name} className="group border border-border bg-surface p-5 transition hover:border-accent"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center bg-surface-2 text-accent"><Icon className="h-5 w-5"/></div><span className="text-[10px] font-bold uppercase tracking-wider text-text-3">Role view</span></div><h2 className="mt-5 text-base font-bold">{name}</h2><div className="mt-2 text-sm font-semibold text-accent">{kpi}</div><p className="mt-2 min-h-10 text-xs leading-5 text-text-2">{detail}</p><Link to="/bookings" className="mt-5 flex items-center gap-2 border-t border-border pt-4 text-xs font-semibold">Open work queue <ArrowRight className="h-3.5 w-3.5"/></Link></article>)}</div></AppShell>; }