/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as BookingsCodeRouteImport } from './routes/bookings.$code'

const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingsCodeRoute = BookingsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => BookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/bookings/$code': typeof BookingsCodeRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/': typeof BookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/bookings/$code': typeof BookingsCodeRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings': typeof BookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/bookings/$code': typeof BookingsCodeRoute
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/': typeof BookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/inventory'
    | '/bookings/$code'
    | '/bookings/new'
    | '/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventory' | '/bookings/$code' | '/bookings/new' | '/bookings'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/inventory'
    | '/bookings/$code'
    | '/bookings/new'
    | '/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  InventoryRoute: typeof InventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/bookings/$code': {
      id: '/bookings/$code'
      path: '/$code'
      fullPath: '/bookings/$code'
      preLoaderRoute: typeof BookingsCodeRouteImport
      parentRoute: typeof BookingsRoute
    }
  }
}

interface BookingsRouteChildren {
  BookingsCodeRoute: typeof BookingsCodeRoute
  BookingsNewRoute: typeof BookingsNewRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsCodeRoute: BookingsCodeRoute,
  BookingsNewRoute: BookingsNewRoute,
  BookingsIndexRoute: BookingsIndexRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRouteWithChildren,
  InventoryRoute: InventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
