/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DamageReportRouteImport } from './routes/damage-report'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as InventoryItemIdRouteImport } from './routes/inventory.$itemId'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as BookingsCodeRouteImport } from './routes/bookings.$code'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageReportRoute = DamageReportRouteImport.update({
  id: '/damage-report',
  path: '/damage-report',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsRoute,
} as any)
const InventoryItemIdRoute = InventoryItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => InventoryRoute,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingsCodeRoute = BookingsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => BookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/damage-report': typeof DamageReportRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/bookings/$code': typeof BookingsCodeRoute
  '/bookings/new': typeof BookingsNewRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/damage-report': typeof DamageReportRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/bookings/$code': typeof BookingsCodeRoute
  '/bookings/new': typeof BookingsNewRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/damage-report': typeof DamageReportRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/bookings/$code': typeof BookingsCodeRoute
  '/bookings/new': typeof BookingsNewRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/damage-report'
    | '/inventory'
    | '/notifications'
    | '/reports'
    | '/staff'
    | '/bookings/$code'
    | '/bookings/new'
    | '/inventory/$itemId'
    | '/bookings/'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/damage-report'
    | '/notifications'
    | '/reports'
    | '/staff'
    | '/bookings/$code'
    | '/bookings/new'
    | '/inventory/$itemId'
    | '/bookings'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/damage-report'
    | '/inventory'
    | '/notifications'
    | '/reports'
    | '/staff'
    | '/bookings/$code'
    | '/bookings/new'
    | '/inventory/$itemId'
    | '/bookings/'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  DamageReportRoute: typeof DamageReportRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ReportsRoute: typeof ReportsRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage-report': {
      id: '/damage-report'
      path: '/damage-report'
      fullPath: '/damage-report'
      preLoaderRoute: typeof DamageReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/inventory/$itemId': {
      id: '/inventory/$itemId'
      path: '/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof InventoryItemIdRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/bookings/$code': {
      id: '/bookings/$code'
      path: '/$code'
      fullPath: '/bookings/$code'
      preLoaderRoute: typeof BookingsCodeRouteImport
      parentRoute: typeof BookingsRoute
    }
  }
}

interface BookingsRouteChildren {
  BookingsCodeRoute: typeof BookingsCodeRoute
  BookingsNewRoute: typeof BookingsNewRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsCodeRoute: BookingsCodeRoute,
  BookingsNewRoute: BookingsNewRoute,
  BookingsIndexRoute: BookingsIndexRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface InventoryRouteChildren {
  InventoryItemIdRoute: typeof InventoryItemIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryItemIdRoute: InventoryItemIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRouteWithChildren,
  DamageReportRoute: DamageReportRoute,
  InventoryRoute: InventoryRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ReportsRoute: ReportsRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
